### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by gonzalo-** [DedBash/WireGuard-VPN-on-Fritz-Box#1]
Hi there, I have a similar setup, but if I check my public ip everywhere I still get the real IP, do you have the same thing? The easiest test is to enter the mullvad website and on the top you will see if you are using or not the vpn.

**Comment by DedBash** [comment]
Hey @gonzalo-,
is the dot at "Remote Connect." green or gray?

![Screenshot_20230818_173915](https://github.com/DedBash/Mullvad-VPN-on-Fritz-Box/assets/79027536/f5bcce79-d1bd-4509-bb3b-2a9f725102ab)

And is the item "Send all IPv4 network traffic via the VPN connection" activated under config (for ipv6 of course also if available)?
![Screenshot_20230818_174124](https://github.com/DedBash/Mullvad-VPN-on-Fritz-Box/assets/79027536/7d13da8d-e479-4424-a059-4b7801f40a99)

**Comment by gonzalo-** [comment]
Yes of course I have all that working and green, but I figured out that for example machines on the guess network are not going through the tunnel and also if you have some NAT ports to internal machines anything will go in the tunnel until you exclude that machine with the NATs from the tunnel connection, which it was what I did and not seems to work (not the guess network), it would be nice to be able to create another tunnel for those.

Thanks for the help :)
