### ISSUE TITLE
Connect device to router from outside your WiFi

### ISSUE THREAD

**Issue by javiergarval** [DedBash/WireGuard-VPN-on-Fritz-Box#3]
Hi, first of all thank you for this tutorial.

I was guessing, is it possible to also connect my phone to my router so I can connect also to the Mullvad VPN even when I can't reach my Wifi?

I have been trying to create another Wireguard configuration for my devices but the Fritzbox rejected due to a network conflict.

Thank you!

**Comment by DedBash** [comment]
That's actually a good question to which I unfortunately don't have an immediate answer, I'll do some testing, but I can't promise you anything

**Comment by DedBash** [comment]
Unfortunately I could not find anything about this and will therefore close this issue
