### ISSUE TITLE
doesn't work phone voip  

### ISSUE THREAD

**Issue by smilzo05** [DedBash/WireGuard-VPN-on-Fritz-Box#4]
hello, thanks for the guide, it works and I can surf the internet through vpn wireguard. with frit!box 7590 if active the vpn does not work the voip phone, can not connect to the services of the isp, error dns. someone has the same problem? there is a solution? thanks

**Comment by DedBash** [comment]
Hi, which VPN provider do you use (something like Mullvad, NordVPN, etc) or do you use something self-hosted?

**Comment by smilzo05** [comment]
Hello,i use  mullvad+TIM (Telecom).
I have read on some forums that other users have the same problem
Thanks

**Comment by DedBash** [comment]
You could try changing the DNS servers in the fritzbox and see if that helps
Here is the list from mullvad itself:
https://github.com/mullvad/dns-blocklists#custom-dns-entries-for-use-with-our-vpn-service

Sorry, my FritzBox is currently set to German but you should recognize what is meant
![image](https://github.com/user-attachments/assets/fcae1b1f-8a90-4a44-9f7e-5962195decdf)

**Comment by smilzo05** [comment]
I use quad9 DNS.
In wg_config  i select alla DNS list (ad-gambling-traking ecc).
Thanks
